name: Export Secret
on: workflow_dispatch

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secret via Base64
        env:
          THE_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          # 将 Secret 转换为 Base64 编码并打印
          echo "Base64 编码后的内容是："
          echo -n "$THE_SECRET" | base64
